MaskMonitoringSystem/WebMaskDetection/Controllers/IncidentReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebMaskDetection.EntityStore;
using WebMaskDetection.Models;

namespace WebMaskDetection.Controllers
{
    public class IncidentReportsController : Controller
    {
        private readonly DatabaseContext _context;

        public IncidentReportsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: IncidentReports
        public async Task<IActionResult> Index()
        {
            var databaseContext = _context.IncidentReport.OrderByDescending(x => x.IncidentDateTime).Include(i => i.LocationSetting);
            return View(await databaseContext.ToListAsync());
        }

        // GET: IncidentReports/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incidentReport = await _context.IncidentReport
                .Include(i => i.LocationSetting)
                .SingleOrDefaultAsync(m => m.IncidentIndex == id);
            if (incidentReport == null)
            {
                return NotFound();
            }

            return View(incidentReport);
        }

        // GET: IncidentReports/Create
        public IActionResult Create()
        {
            ViewData["LocationIndex"] = new SelectList(_context.LocationSetting, "locationIndex", "locationIndex");
            return View();
        }

        // POST: IncidentReports/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IncidentIndex,LocationIndex,IncidentDateTime,Note")] IncidentReport incidentReport)
        {
            if (ModelState.IsValid)
            {
                _context.Add(incidentReport);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationIndex"] = new SelectList(_context.LocationSetting, "locationIndex", "locationIndex", incidentReport.LocationIndex);
            return View(incidentReport);
        }

        // GET: IncidentReports/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incidentReport = await _context.IncidentReport.SingleOrDefaultAsync(m => m.IncidentIndex == id);
            if (incidentReport == null)
            {
                return NotFound();
            }
            ViewData["LocationIndex"] = new SelectList(_context.LocationSetting, "locationIndex", "Location", incidentReport.LocationIndex);
            return View(incidentReport);
        }

        // POST: IncidentReports/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IncidentIndex,LocationIndex,IncidentDateTime,Note")] IncidentReport incidentReport)
        {
            if (id != incidentReport.IncidentIndex)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(incidentReport);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IncidentReportExists(incidentReport.IncidentIndex))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationIndex"] = new SelectList(_context.LocationSetting, "locationIndex", "locationIndex", incidentReport.LocationIndex);
            return View(incidentReport);
        }

        // GET: IncidentReports/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var incidentReport = await _context.IncidentReport
                .Include(i => i.LocationSetting)
                .SingleOrDefaultAsync(m => m.IncidentIndex == id);
            if (incidentReport == null)
            {
                return NotFound();
            }

            return View(incidentReport);
        }

        // POST: IncidentReports/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var incidentReport = await _context.IncidentReport.SingleOrDefaultAsync(m => m.IncidentIndex == id);
            _context.IncidentReport.Remove(incidentReport);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IncidentReportExists(int id)
        {
            return _context.IncidentReport.Any(e => e.IncidentIndex == id);
        }
    }
}

MaskMonitoringSystem/WebMaskDetection/Controllers/LocationEmailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebMaskDetection.EntityStore;
using WebMaskDetection.Models;

namespace WebMaskDetection.Controllers
{
    public class LocationEmailsController : Controller
    {
        private readonly DatabaseContext _context;

        public LocationEmailsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: LocationEmails
        public async Task<IActionResult> Index()
        {
            var databaseContext = _context.LocationEmail.Include(l => l.LocationSetting);
            return View(await databaseContext.ToListAsync());
        }

        // GET: LocationEmails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var locationEmail = await _context.LocationEmail
                .Include(l => l.LocationSetting)
                .SingleOrDefaultAsync(m => m.LE_Index == id);
            if (locationEmail == null)
            {
                return NotFound();
            }

            return View(locationEmail);
        }

        // GET: LocationEmails/Create
        public IActionResult Create()
        {
            ViewData["LocationIndex"] = new SelectList(_context.LocationSetting, "locationIndex", "Location");
            return View();
        }

        // POST: LocationEmails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LE_Index,LocationIndex,Email")] LocationEmail locationEmail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(locationEmail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationIndex"] = new SelectList(_context.LocationSetting, "locationIndex", "Location", locationEmail.LocationIndex);
            return View(locationEmail);
        }

        // GET: LocationEmails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var locationEmail = await _context.LocationEmail.SingleOrDefaultAsync(m => m.LE_Index == id);
            if (locationEmail == null)
            {
                return NotFound();
            }
            ViewData["LocationIndex"] = new SelectList(_context.LocationSetting, "locationIndex", "Location", locationEmail.LocationIndex);
            return View(locationEmail);
        }

        // POST: LocationEmails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LE_Index,LocationIndex,Email")] LocationEmail locationEmail)
        {
            if (id != locationEmail.LE_Index)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(locationEmail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationEmailExists(locationEmail.LE_Index))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LocationIndex"] = new SelectList(_context.LocationSetting, "locationIndex", "Location", locationEmail.LocationIndex);
            return View(locationEmail);
        }

        // GET: LocationEmails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var locationEmail = await _context.LocationEmail
                .Include(l => l.LocationSetting)
                .SingleOrDefaultAsync(m => m.LE_Index == id);
            if (locationEmail == null)
            {
                return NotFound();
            }

            return View(locationEmail);
        }

        // POST: LocationEmails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var locationEmail = await _context.LocationEmail.SingleOrDefaultAsync(m => m.LE_Index == id);
            _context.LocationEmail.Remove(locationEmail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationEmailExists(int id)
        {
            return _context.LocationEmail.Any(e => e.LE_Index == id);
        }
    }
}

MaskMonitoringSystem/WebMaskDetection/Controllers/LocationSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebMaskDetection.Models;
using WebMaskDetection.EntityStore;

namespace WebMaskDetection.Controllers
{
    public class LocationSettingsController : Controller
    {
        private readonly DatabaseContext _context;

        public LocationSettingsController(DatabaseContext context)
        {
            _context = context;
        }

        // GET: LocationSettings
        public async Task<IActionResult> Index()
        {
            return View(await _context.LocationSetting.ToListAsync());
        }

        // GET: LocationSettings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var locationSetting = await _context.LocationSetting
                .SingleOrDefaultAsync(m => m.locationIndex == id);
            if (locationSetting == null)
            {
                return NotFound();
            }

            return View(locationSetting);
        }

        // GET: LocationSettings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LocationSettings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("locationIndex,Location")] LocationSetting locationSetting)
        {
            if (ModelState.IsValid)
            {
                _context.Add(locationSetting);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(locationSetting);
        }

        // GET: LocationSettings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var locationSetting = await _context.LocationSetting.SingleOrDefaultAsync(m => m.locationIndex == id);
            if (locationSetting == null)
            {
                return NotFound();
            }
            return View(locationSetting);
        }

        // POST: LocationSettings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("locationIndex,Location")] LocationSetting locationSetting)
        {
            if (id != locationSetting.locationIndex)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(locationSetting);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LocationSettingExists(locationSetting.locationIndex))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(locationSetting);
        }

        // GET: LocationSettings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var locationSetting = await _context.LocationSetting
                .SingleOrDefaultAsync(m => m.locationIndex == id);
            if (locationSetting == null)
            {
                return NotFound();
            }

            return View(locationSetting);
        }

        // POST: LocationSettings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var locationSetting = await _context.LocationSetting.SingleOrDefaultAsync(m => m.locationIndex == id);
            _context.LocationSetting.Remove(locationSetting);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LocationSettingExists(int id)
        {
            return _context.LocationSetting.Any(e => e.locationIndex == id);
        }
    }
}

MaskMonitoringSystem/WebMaskDetection/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMaskDetection</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color:darkblue">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="font-size:24px;color:white;font-weight:600" >Mask Monitoring System</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="WebCamPredictSettings" asp-action="Index" style="font-size:15px;color:white;font-weight:600">Time Interval/Probability</a></li>
                    <li><a asp-area="" asp-controller="IncidentReports" asp-action="Index" style="font-size:15px;color:white;font-weight:600">Incidents Review</a></li>
                    <li><a asp-area="" asp-controller="LocationSettings" asp-action="Index" style="font-size:15px;color:white;font-weight:600">Set Location</a></li>
                    <li><a asp-area="" asp-controller="LocationEmails" asp-action="Index" style="font-size:15px;color:white;font-weight:600">Location Email</a></li>
                    <li><a asp-area="" asp-controller="LocationTelegrams" asp-action="Index" style="font-size:15px;color:white;font-weight:600">Location Telegram</a></li>

                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - Mask Monitoring System</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>